language: python

python:
  - "3.10"

env:
  global:
    secure: "S+PZE9BSwczIg3d/4Wk7/PGJLWZ6KO7ifyLbMznIcB86t+iLnaQ1fbsZCqQG0j0TMfHZwdsw1+FpqrWYzVm/KgwIQqy8Peen0KJWunio3ik0Ljuh4HKetNEt0AHBclPV3tKXghP3oJgybm/iMe06+OXWczxjn9nFPqgTN2hmFFCPB7VmMBo74PesCSi02taWPhsHzLDuO0lUNJFoFl2nkH8zwpLFGLOND+kUc2z4N6XywFpLRMzCCd9hnUA+4vxmAYwR2Tje64jGfuTWm5p8u5sNp9xrH5MEB7unYL6yGP5VBOUC/42+2YodkCIgE87GkvHAMAinIpbqmVTWDRupSn4PZAQPdFzQpeGNbUS1HA1a7TqLNFU9LHcxjmwRzV5u5xil1yxlqRg+LyOCONgx7o6IH1MLvx+srv8f+Xw/zmoXKR+99G01xaL8mUz/P2tkgv9/AVDctIgkc35Bl6334k9q/hgLrVw8N4AdN+kKDZOJuvxlrwzdAEAb245qFbdAQnPxZwmnb6lG6pCAhtsPQiq/fy2C2W3V5gX2Z7M8a/AyMhqtPj8Sp6hCnqyX5V8CF6ddUdP0jC1085BenPgWpYv+RCGJwPpVxHQ6IMINLA2fCpuDy1wQoNwcvvjr8HQ6qz1RLou1Ts3JexXT/PE5MxaPvEZjMv/QnjrGd73GkEY="

jobs:
  include:
    # Deploy stage to create Github release and deploy to PyPi after default test stage is completed.
    - stage: deploy
      python: "3.10"
      script:
        - poetry config pypi-token.pypi $PYPI_APIKEY
        - poetry build
      deploy:
        - provider: script
          on:
            repo: asandeep/diffuse
            tags: true
          script: poetry publish
          skip_cleanup: true
        - provider: releases
          api_key:
            secure: G0XU6goR7i+y1iqIxhHugyMYxY+5dy7L47LATRM7B7zZkg5fezx0IUS44f33sDXrCmQ1b05/gkL1fN9GlxmKkeRcFrSVrpAwhjO7W7yfRN3ztdXBwhPZYbDVzif5DNkLcOJjHg1dtBz+xZaLz4cqkaN/HUiHsaBlcmBt9VILAZojQs+Q2GJZp9AQOHQlPjyRCsC9hX8sxVwU4tDVyrZO1n5Hxi7gxetvuimce2ckWdpK61S4sTBCFjmEbsxHMX9DbQmISqD0nkQ80BEkqFQ24x1C+n3hOxy4AHl8NURP+WQuPKZLUg+abMGxazw+H0qBH3SkIihGsQizKFV3wPfbuCCqH5mGqqY/jYEk2Wdf9kJyQRhnAuDdwWfJKArVk26F14xJAMCDOkZEtZ0+WVJrMwcF4VVydFXQY9UKQ0oM/8XSWwkZA9v53J3hwHRLEMoQPByNHZRjUEtzTNxb4IpbNuNTI6PP2gmqF9eitK/hhR3Wg9sLMbuJAlyLLO2djfN5pYYPmppeK+KqbrfVnkxQjdjRXgabJ4Iq+AWYBO9l1PyVf3a92PX5vm6joUU4cncNanAsl6rL8dklJITU2ka0hjKwdTT1Wjhq2s58Y3T9BS79UmxeWMEoV9YVBTKR9gaXRHtbQW1RRaMqMpMSVZ0U/SLs8kmNBrLm/jBNLW40nOE=
          file: dist/*.tar.gz
          file_glob: true
          on:
            repo: asandeep/diffuse
            tags: true
          skip_cleanup: true

install:
  - pip install poetry tox-travis codecov
script:
  - tox
after_success:
  - codecov
